Repository teksi/wastewater, pull requests merged in 2024-03, with the labels that each got.

#158 add missing cyclic relations
  datamodel/changelogs/0001/03_tww_db_dss.sql
Labels: bug, datamodel

#164 Add DEFAULT FALSE on organisation flags
  datamodel/app/organisation_functions.sql
  datamodel/changelogs/0001/05_data_model_extensions.sql
Labels: fix

#186 Update README.md
  README.md
Labels: enhancement
