Repository teksi/wastewater, pull requests merged in 2024-07, with the labels that each got.

#281 fix label export orientation
  plugin/teksi_wastewater/interlis/interlis_importer_exporter.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
Labels: fix, INTERLIS

#277 Corrections user-guide
  docs/en/user-guide/editing/maintenance_events.rst
  docs/en/user-guide/layerexplanations/layerexplanation.rst
  docs/en/user-guide/layerexplanations/namingconventions.rst
  docs/en/user-guide/layerexplanations/overview.rst
Labels: documentation

#288 bump pirogue
  datamodel/requirements.txt
Labels: datamodel, fix

#294 Adapt images for tww INTERLIS import
  docs/en/admin-guide/interlis-io/images/tww_interlis_export.png
  docs/en/admin-guide/interlis-io/images/tww_interlis_export_selection.png
  docs/en/admin-guide/interlis-io/index.rst
Labels: documentation

#290 new project chapter in Userguide/Overview
  docs/en/user-guide/layerexplanations/images/layerorder.jpg
  docs/en/user-guide/layerexplanations/images/mapthemes.jpg
  docs/en/user-guide/layerexplanations/images/project_properties.jpg
  docs/en/user-guide/layerexplanations/images/properties_datasources.jpg
  docs/en/user-guide/layerexplanations/images/properties_projectcolors.jpg
  docs/en/user-guide/layerexplanations/images/properties_projectcolors_example1.jpg
  docs/en/user-guide/layerexplanations/images/properties_variables.jpg
  docs/en/user-guide/layerexplanations/images/properties_variables_example1.jpg
  docs/en/user-guide/layerexplanations/images/teksiabwasser.png
  docs/en/user-guide/layerexplanations/index.rst
  docs/en/user-guide/layerexplanations/overview.rst
  docs/en/user-guide/layerexplanations/twwproject.rst
Labels: documentation

#304 2024-07-11-interlis-import-fix-references-value-lists
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_importer_to_intermediate_schema.py
Labels: fix

#302 check validity of presets on startup
  plugin/teksi_wastewater/teksi_wastewater_plugin.py
  plugin/teksi_wastewater/utils/tww_validity_check.py
Labels: enhancement

#174 Add view for detailgeometry
  datamodel/app/create_app.py
  datamodel/app/view/vw_wastewater_structure.py
Labels: enhancement, datamodel

#301 set organisation.tww_active after import
  datamodel/app/create_app.py
  datamodel/app/organisation_functions.sql
  plugin/teksi_wastewater/interlis/interlis_importer_exporter.py
Labels: enhancement, datamodel, plugin, feature

#310 2024 07 15 minimal dataset kek improvements
  plugin/teksi_wastewater/tests/data/minimal-dataset-transferdatensatz_VSA-KEK-channel-damage.xtf
  plugin/teksi_wastewater/tests/data/minimal-dataset-transferdatensatz_VSA-KEK-manhole-damage.xtf
Labels: enhancement, INTERLIS

#266 2024 06 21 adapt filtering export selection
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/model_tww_od.py
Labels: bug

#284 Only export einzugsgebiet_text for VSA DSS
  plugin/teksi_wastewater/interlis/config.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
Labels: fix, INTERLIS

#296 add subclass checks
  plugin/teksi_wastewater/interlis/interlis_importer_exporter.py
Labels: fix, INTERLIS, sustainability

#179 add view for catchment area totals
  datamodel/app/create_app.py
  datamodel/app/gep_views/vw_tww_catchment_area_totals.sql
Labels: enhancement, datamodel

#314 Fix About Dialog
  plugin/teksi_wastewater/gui/about_dialog.py
  plugin/teksi_wastewater/metadata.txt
  plugin/teksi_wastewater/teksi_wastewater_plugin.py
  plugin/teksi_wastewater/ui/about_dialog.ui
  plugin/teksi_wastewater/ui/dlgabout.ui
Labels: plugin, fix, sustainability

#321 Move fix to #241 to separate PR
  datamodel/app/view/vw_tww_wastewater_structure.py
Labels: fix

#175 add function to calculate catchment area totals from catchment areas
  datamodel/app/create_app.py
  datamodel/app/update_catchment_area_totals.sql
  datamodel/app/view/catchment_area/vw_catchment_area_totals_aggregated.sql
Labels: documentation, enhancement

#334 Unload SymbologyTriggerAction
  plugin/teksi_wastewater/teksi_wastewater_plugin.py
Labels: plugin

#335 2024-07-26-adapt-documentation-interlis-import-export-etc
  docs/conf.py
  docs/en/admin-guide/datamodel-tool/images/tww_sys.oid_prefixes.png
  docs/en/admin-guide/datamodel-tool/index.rst
  docs/en/admin-guide/db-production-readiness/index.rst
  docs/en/admin-guide/interlis-io/images/interlis_export_button.png
  docs/en/admin-guide/interlis-io/images/interlis_import_button.png
  docs/en/admin-guide/interlis-io/images/layer_vw_tww_reach_beschriftungsueberlauf.png
  docs/en/admin-guide/interlis-io/images/layer_vw_tww_reach_label_overrun.png
  docs/en/admin-guide/interlis-io/images/toolbar.png
  docs/en/admin-guide/interlis-io/index.rst
  docs/en/installation-guide/images/tww_project_qm_language_files.jpg
  docs/en/user-guide/How-To/images/configuration_default_values.png
  docs/en/user-guide/How-To/images/default_values_fieldname_selection.png
  docs/en/user-guide/How-To/images/default_values_organisation_obj_id_selection.png
  docs/en/user-guide/How-To/index.rst
  docs/en/user-guide/editing/editing.rst
  docs/en/user-guide/editing/images/form_vw_qgep_reach.jpg
  docs/en/user-guide/editing/images/form_vw_qgep_reach_reachpoints.jpg
  docs/en/user-guide/editing/images/form_vw_qgep_wastewater_structure_structure_parts.jpg
  docs/en/user-guide/editing/images/form_vw_tww_cover.jpg
  docs/en/user-guide/editing/images/form_vw_tww_cover_structure_parts.jpg
  docs/en/user-guide/editing/images/form_vw_tww_cover_wastewater_nodes.jpg
  docs/en/user-guide/editing/images/qgep_info_button_rightclick.jpg
  docs/en/user-guide/editing/images/qgep_toolbox.jpg
  docs/en/user-guide/editing/images/tww_info_button.jpg
Labels: documentation
