Repository teksi/wastewater, pull requests merged in 2024-04, with the labels that each got.

#185 Upgrade Postgis
  .env.example
  datamodel/.docker/Dockerfile
  docker-compose.yml
  plugin/teksi_wastewater/interlis/utils/various.py
Labels: fix

#198 add psycopg2 support
  plugin/.docker/Dockerfile
  plugin/teksi_wastewater/interlis/interlis_importer_exporter.py
  plugin/teksi_wastewater/processing_provider/TwwSwmm.py
Labels: enhancement, plugin, sustainability

#202 Fix lenght of labels OID suffix and hardcoded shortcut_en
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
Labels: fix

#191 DSS export fixes
  plugin/.docker/run-docker-tests.sh
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_importer_to_intermediate_schema.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/model_tww_od.py
  plugin/teksi_wastewater/tests/test_interlis.py
Labels: fix

#203 Mask password in logs when calling interlis utilities
  plugin/teksi_wastewater/interlis/utils/ili2db.py
  plugin/teksi_wastewater/interlis/utils/various.py
Labels: security

#207 include oid_prefix in interlis text class export
  plugin/teksi_wastewater/interlis/config.py
  plugin/teksi_wastewater/interlis/interlis_importer_exporter.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/model_tww.py
Labels: enhancement, datamodel, review

#212 set order_usage_current
  datamodel/changelogs/0001/05_data_model_extensions.sql
Labels: datamodel

#218 Fix pre-commit error
  datamodel/test/test_geometry.py
Labels: CI/CD

#214 2024-04-22-patch-datatypes_postgres
  datamodel/changelogs/0001/03_tww_db_dss.sql
  datamodel/changelogs/0001/09_tww_dictionaries.sql
  datamodel/changelogs/0001/09_tww_dictionaries_kek.sql
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_importer_to_intermediate_schema.py
Labels: datamodel, fix
