Repository teksi/wastewater, pull requests merged in 2024-02, with the labels that each got.

#141 Fix doc translated links
  docs/en/translation/index.rst
Labels: documentation, fix, translation

#151 fix reach progression alternative 2 (replaces fix reach progression alternative)
  datamodel/changelogs/0001/03_tww_db_dss.sql
  datamodel/changelogs/0001/09_tww_dictionaries.sql
Labels: fix

#121 Import export of reach_progression_alternative
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_importer_to_intermediate_schema.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/model_interlis_sia405_abwasser.py
  plugin/teksi_wastewater/interlis/interlis_model_mapping/model_tww_od.py
Labels: datamodel, fix

#160 Fix doc broken link
  docs/en/translation/index.rst
Labels: fix
