Repository teksi/wastewater, pull requests merged in 2024-06, with the labels that each got.

#263 add update_*_symbology queries to import process
  plugin/teksi_wastewater/interlis/interlis_importer_exporter.py
  plugin/teksi_wastewater/interlis/utils/various.py
  plugin/teksi_wastewater/teksi_wastewater_plugin.py
Labels: fix

#271 Add sqlalchemy and geoalchemy2 to prerequisites docs
  docs/en/installation-guide/requirements.rst
Labels: documentation

#269 Remove QGEP and fix teksi wastewater urls
  plugin/teksi_wastewater/metadata.txt
  plugin/teksi_wastewater/teksi_wastewater_plugin.py
Labels: plugin
