Repository teksi/wastewater, pull requests merged in 2025-01, with the labels that each got.

#523 Try upgrade to ubuntu 24.04 LTS
  .github/workflows/datamodel-create-dumps.yml
  .github/workflows/datamodel-test.yml
  .github/workflows/docs-builder.yml
  .github/workflows/plugin-package.yml
  .github/workflows/plugin-test.yml
  .github/workflows/project-translation.yml
Labels: CI/CD, sustainability

#524 Fixes to MultipleInheritances
  datamodel/app/create_app.py
  datamodel/app/view/vw_maintenance_event.yaml
  datamodel/app/view/vw_oo_overflow.yaml
Labels: fix, app_schema

#539 add label and symbology custiomisation guide to docs
  docs/en/admin-guide/db-label-customisation/index.rst
  docs/en/admin-guide/index.rst
Labels: documentation
