Repository teksi/wastewater, pull requests merged in 2025-05, with the labels that each got.

#593 2025 04 15 add interlis test datasets sia405 pt cc
  plugin/teksi_wastewater/tests/data/minimal-dataset-SIA405-FERNWIRKKABEL.xtf
  plugin/teksi_wastewater/tests/data/minimal-dataset-SIA405-SCHUTZROHR.xtf
Labels: enhancement, datamodel, feature

#531 Add aggregation view for channel and georeferenced channel damages
  datamodel/app/create_app.py
  datamodel/app/view/vw_tww_channel.py
  datamodel/app/view/vw_tww_damage_channel.py
Labels: app_schema

#599 Delete datamodel/changelogs/0001/09_ww_control_cable_dictionaries.sql
  datamodel/changelogs/0001/09_ww_control_cable_dictionaries.sql
Labels: fix
