Repository teksi/wastewater, pull requests merged in 2025-04, with the labels that each got.

#577 2025-03-31-fix-images-docs
  docs/conf.py
  docs/en/user-guide/layerexplanations/images/schema_vw_tww_reach.jpg
  docs/en/user-guide/layerexplanations/images/schema_vw_tww_wastewater_structure.jpg
Labels: documentation, fix

#573 Update README.md
  README.md
Labels: documentation, fix

#578 2025 03 21 oid documentation update
  docs/en/installation-guide/images/001_searchplugin.jpeg
  docs/en/installation-guide/images/add_own_oid_prefix.jpg
  docs/en/installation-guide/images/tww_project_qm_language_files.jpg
  docs/en/installation-guide/workstation.rst
  docs/en/user-guide/digitizing/images/button_data_entry_wizard_selected.jpg
Labels: documentation, fix

#528 Upgrade to postgres 16 postgis 3.5
  .env.example
  datamodel/.docker/Dockerfile
  docker-compose.yml
Labels: CI/CD, sustainability

#579 Fix docs links for demo data and project download
  docs/en/installation-guide/workstation.rst
Labels: documentation, fix

#583 2025-04-07-fix-docu-image-link
  docs/en/admin-guide/db-production-readiness/images/tww_sys.oid_prefixes.png
  docs/en/user-guide/How-To/index.rst
Labels: documentation

#544 Prevent view crashing if `ST_LENGTH(re.progression3d_geometry)` is null or 0
  datamodel/app/view/vw_tww_reach.py
Labels: datamodel, fix

#516 Adapt Readme.md for 2024.0
  README.md
Labels: documentation

#591 2025-04-10-update-map-themes
  docs/en/user-guide/layerexplanations/images/overview_map_theme.png
  docs/en/user-guide/layerexplanations/images/renovation_necessity_map_theme.png
  docs/en/user-guide/layerexplanations/images/usage_current_map_theme.png
  docs/en/user-guide/layerexplanations/images/vw_tww_reach_themes.png
  docs/en/user-guide/layerexplanations/images/vw_tww_wastewater_structure_themes.png
  docs/en/user-guide/layerexplanations/twwproject.rst
Labels: documentation

#590 2025-04-10-documentation-organisations
  docs/en/admin-guide/interlis-io/index.rst
  docs/en/user-guide/How-To/index.rst
Labels: documentation

#585 Add flag to initialise prefix path on interlis cmd
  plugin/tww_cmd.py
Labels: INTERLIS
