Repository teksi/wastewater, pull requests merged in 2025-03, with the labels that each got.

#555 Fix SQL Error in _export_re_building_group_disposal
  plugin/teksi_wastewater/interlis/interlis_model_mapping/interlis_exporter_to_intermediate_schema.py
Labels: plugin, fix, INTERLIS

#527 Update initialisation docs
  docs/en/index.rst
  docs/en/installation-guide/database-initialization.rst
Labels: documentation, fix

#567 Update twwprofiledockwidget.py
  plugin/teksi_wastewater/gui/twwprofiledockwidget.py
Labels: enhancement, fix

#561 2025-03-25-fix-default-digitize-drainage-channel
  plugin/teksi_wastewater/tools/twwmaptooladdfeature.py
Labels: enhancement, fix
